In [16]:
%matplotlib inline
import matplotlib.pyplot as plt

In [1]:
import pandas as pd
datasetx = pd.read_csv('combined_filtered.csv',error_bad_lines=False)
datasetx.info()

C:\Users\user\AppData\Local\Temp\ipykernel_13716\1825867264.py:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  datasetx = pd.read_csv('combined_filtered.csv',error_bad_lines=False)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1727654 entries, 0 to 1727653
Data columns (total 62 columns):
 #   Column                    Dtype  
---  ------                    -----  
 0   Unnamed: 0                int64  
 1   QUARTER                   int64  
 2   MONTH                     int64  
 3   DAY_OF_MONTH              int64  
 4   DAY_OF_WEEK               int64  
 5   OP_UNIQUE_CARRIER         object 
 6   ORIGIN                    object 
 7   DEST                      object 
 8   CRS_DEP_TIME              int64  
 9   DEP_DEL15                 float64
 10  DEP_DELAY_GROUP           float64
 11  DEP_TIME_BLK              object 
 12  CRS_ARR_TIME              int64  
 13  ARR_DEL15                 float64
 14  ARR_DELAY_GROUP           float64
 15  ARR_TIME_BLK              object 
 16  CANCELLED                 float64
 17  CRS_ELAPSED_TIME          float64
 18  DISTANCE                  float64
 19  Origin_max_temp           int64  
 20  Origin_min_temp         

In [2]:
datasetx = datasetx.drop(['QUARTER','Dest_space','DEP_TIME_BLK','ARR_TIME_BLK','Origin_space','Unnamed: 0','OP_UNIQUE_CARRIER','ORIGIN','DEST'],axis=1)

In [3]:
datasetx['TOTAL_DELAY'].fillna(-1000,inplace=True)

In [4]:
delay_array = datasetx['TOTAL_DELAY']

In [5]:
datasetx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1727654 entries, 0 to 1727653
Data columns (total 53 columns):
 #   Column                    Dtype  
---  ------                    -----  
 0   MONTH                     int64  
 1   DAY_OF_MONTH              int64  
 2   DAY_OF_WEEK               int64  
 3   CRS_DEP_TIME              int64  
 4   DEP_DEL15                 float64
 5   DEP_DELAY_GROUP           float64
 6   CRS_ARR_TIME              int64  
 7   ARR_DEL15                 float64
 8   ARR_DELAY_GROUP           float64
 9   CANCELLED                 float64
 10  CRS_ELAPSED_TIME          float64
 11  DISTANCE                  float64
 12  Origin_max_temp           int64  
 13  Origin_min_temp           int64  
 14  Origin_avg_temp           int64  
 15  Origin_dep_temp           int64  
 16  Origin_ADP_temp           float64
 17  Origin_AWB_temp           float64
 18  Origin_degree_days_heat   int64  
 19  Origin_degree_days_cool   int64  
 20  Origin_snow_depth       

In [6]:
len(delay_array)

1727654

In [7]:
type(delay_array)

pandas.core.series.Series

In [8]:
delay_array.describe()

count    1.727654e+06
mean     2.916216e+01
std      9.909899e+01
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      1.700000e+01
max      6.145000e+03
Name: TOTAL_DELAY, dtype: float64

In [9]:
import numpy as np
class_label = [None] * 1727654

for i in range(len(delay_array)):
    if delay_array[i] ==0 :
        class_label[i]='Nd'
    elif delay_array[i]>0 and delay_array[i]<=15:
        class_label[i]='A'
    elif delay_array[i]>15 and delay_array[i]<=30:
        class_label[i]='B'
    elif delay_array[i]>30 and delay_array[i]<=45:
        class_label[i]='C'
    elif delay_array[i]>45 and delay_array[i]<=60:
        class_label[i]='D'
    elif delay_array[i]>60:
        class_label[i]='E'
    elif delay_array[i]==-1000:
        class_label[i]='CN'
        

In [10]:
df=pd.DataFrame({'col':class_label})

In [11]:
datasetx = pd.concat([datasetx, df],axis=1)

In [12]:
datasetx.sample(5)

MONTH  DAY_OF_MONTH  DAY_OF_WEEK  CRS_DEP_TIME  DEP_DEL15  \
955210      12            19            7          2010        0.0   
1637732      3            31            4          1800        0.0   
604713       9            29            3           725        1.0   
445782       9            13            1           930        1.0   
103641       6             7            1          1515        0.0   

         DEP_DELAY_GROUP  CRS_ARR_TIME  ARR_DEL15  ARR_DELAY_GROUP  CANCELLED  \
955210              -1.0          2206        0.0             -1.0        0.0   
1637732              0.0          2123        1.0              2.0        0.0   
604713               5.0          1516        1.0              3.0        0.0   
445782               5.0          1110        1.0              4.0        0.0   
103641               0.0          1810        0.0             -1.0        0.0   

         ...  Dest_pressure_avg_SL  Dest_?1  Dest_?2  Dest_wind  \
955210   ...                 29.78     10.3     20.0       12.2   
1637732  ...                 29.81      1.5     31.0        3.9   
604713   ...                 30.04      7.0      3.0        8.3   
445782   ...                 29.85      2.4     22.0        8.5   
103641   ...                 29.79      5.8     22.0        6.9   

         Dest_peak_speed  Dest_peak_dir  Dest_sust_speed  Dest_sust_dir  \
955210                35            180             26.0            190   
1637732               25            310             14.0            300   
604713                23             70             13.0             20   
445782                22            240             15.0            110   
103641                23            220             17.0            220   

         TOTAL_DELAY  col  
955210           0.0   Nd  
1637732         43.0    C  
604713         136.0    E  
445782         149.0    E  
103641          14.0    A  

[5 rows x 54 columns]

In [13]:
datasetx['col'].unique()

array(['A', 'Nd', 'E', 'B', 'D', 'C'], dtype=object)

In [14]:
datasetx.corr().style.background_gradient(cmap='coolwarm')

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\formats\style.py:3555: RuntimeWarning: All-NaN slice encountered
  smin = np.nanmin(gmap) if vmin is None else vmin
C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\formats\style.py:3556: RuntimeWarning: All-NaN slice encountered
  smax = np.nanmax(gmap) if vmax is None else vmax


In [15]:
# Load libraries
from sklearn.ensemble import AdaBoostClassifier
from sklearn import datasets

In [16]:
# Create adaboost-decision tree classifer object
clf = AdaBoostClassifier(n_estimators=10,
                         learning_rate=1,
                         random_state=0)

In [17]:
X=datasetx.iloc[:,:-1]
y=datasetx.iloc[:,-1]

In [18]:
X.fillna(0,inplace=True)

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2,random_state=42)

In [20]:
model = clf.fit(X_train,y_train)

In [21]:
y_pred=clf.predict(X_test)

In [30]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
print("\n")
print(cm)

0.8583831841426673


[[ 73598      0      0      0      0      0]
 [ 25257      0      0      0      0      0]
 [ 14282      0      0      0      0      0]
 [  9394      0      0      0      0      0]
 [     0      0      0      0  42116      0]
 [     0      0      0      0      0 180884]]


In [24]:
model.score(X_test,y_test)

0.8583831841426673